package com.bupocket.database.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bupocket.model.TokenTxInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TOKEN_TX_INFO".
*/
public class TokenTxInfoDao extends AbstractDao<TokenTxInfo, String> {

    public static final String TABLENAME = "TOKEN_TX_INFO";

    /**
     * Properties of entity TokenTxInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property TxAccountAddress = new Property(0, String.class, "txAccountAddress", false, "TX_ACCOUNT_ADDRESS");
        public final static Property TxDate = new Property(1, String.class, "txDate", false, "TX_DATE");
        public final static Property TxAmount = new Property(2, String.class, "txAmount", false, "TX_AMOUNT");
        public final static Property TxStatus = new Property(3, String.class, "txStatus", false, "TX_STATUS");
        public final static Property OutinType = new Property(4, String.class, "outinType", false, "OUTIN_TYPE");
        public final static Property TxHash = new Property(5, String.class, "txHash", false, "TX_HASH");
        public final static Property OptNo = new Property(6, String.class, "optNo", true, "OPT_NO");
    }


    public TokenTxInfoDao(DaoConfig config) {
        super(config);
    }
    
    public TokenTxInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TOKEN_TX_INFO\" (" + //
                "\"TX_ACCOUNT_ADDRESS\" TEXT," + // 0: txAccountAddress
                "\"TX_DATE\" TEXT," + // 1: txDate
                "\"TX_AMOUNT\" TEXT," + // 2: txAmount
                "\"TX_STATUS\" TEXT," + // 3: txStatus
                "\"OUTIN_TYPE\" TEXT," + // 4: outinType
                "\"TX_HASH\" TEXT," + // 5: txHash
                "\"OPT_NO\" TEXT PRIMARY KEY NOT NULL );"); // 6: optNo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TOKEN_TX_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TokenTxInfo entity) {
        stmt.clearBindings();
 
        String txAccountAddress = entity.getTxAccountAddress();
        if (txAccountAddress != null) {
            stmt.bindString(1, txAccountAddress);
        }
 
        String txDate = entity.getTxDate();
        if (txDate != null) {
            stmt.bindString(2, txDate);
        }
 
        String txAmount = entity.getTxAmount();
        if (txAmount != null) {
            stmt.bindString(3, txAmount);
        }
 
        String txStatus = entity.getTxStatus();
        if (txStatus != null) {
            stmt.bindString(4, txStatus);
        }
 
        String outinType = entity.getOutinType();
        if (outinType != null) {
            stmt.bindString(5, outinType);
        }
 
        String txHash = entity.getTxHash();
        if (txHash != null) {
            stmt.bindString(6, txHash);
        }
 
        String optNo = entity.getOptNo();
        if (optNo != null) {
            stmt.bindString(7, optNo);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TokenTxInfo entity) {
        stmt.clearBindings();
 
        String txAccountAddress = entity.getTxAccountAddress();
        if (txAccountAddress != null) {
            stmt.bindString(1, txAccountAddress);
        }
 
        String txDate = entity.getTxDate();
        if (txDate != null) {
            stmt.bindString(2, txDate);
        }
 
        String txAmount = entity.getTxAmount();
        if (txAmount != null) {
            stmt.bindString(3, txAmount);
        }
 
        String txStatus = entity.getTxStatus();
        if (txStatus != null) {
            stmt.bindString(4, txStatus);
        }
 
        String outinType = entity.getOutinType();
        if (outinType != null) {
            stmt.bindString(5, outinType);
        }
 
        String txHash = entity.getTxHash();
        if (txHash != null) {
            stmt.bindString(6, txHash);
        }
 
        String optNo = entity.getOptNo();
        if (optNo != null) {
            stmt.bindString(7, optNo);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6);
    }    

    @Override
    public TokenTxInfo readEntity(Cursor cursor, int offset) {
        TokenTxInfo entity = new TokenTxInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // txAccountAddress
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // txDate
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // txAmount
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // txStatus
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // outinType
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // txHash
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // optNo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TokenTxInfo entity, int offset) {
        entity.setTxAccountAddress(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTxDate(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTxAmount(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTxStatus(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOutinType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTxHash(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOptNo(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final String updateKeyAfterInsert(TokenTxInfo entity, long rowId) {
        return entity.getOptNo();
    }
    
    @Override
    public String getKey(TokenTxInfo entity) {
        if(entity != null) {
            return entity.getOptNo();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TokenTxInfo entity) {
        return entity.getOptNo() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
